"""add bank account to expenses

Revision ID: 1d1529358e1e
Revises: c790624d5540
Create Date: 2026-08-07 22:42:09.393253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1529358e1e'
down_revision: Union[str, Sequence[str], None] = 'c790624d5540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "expenses",
        sa.Column(
            "bank_account_id",
            sa.Integer(),
            nullable=True
        )
    )

    op.create_foreign_key(
        "fk_expenses_bank_account_id",
        "expenses",
        "bank_accounts",
        ["bank_account_id"],
        ["id"]
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'bank_account_id')
    # ### end Alembic commands ###
