"""add account number and unique bank account constraint

Revision ID: 21843badd5fb
Revises: d17081e323a3
Create Date: 2026-08-12 13:46:59.958815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21843badd5fb'
down_revision: Union[str, Sequence[str], None] = 'd17081e323a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('account_number', sa.String(), nullable=True))
    op.create_unique_constraint('uq_user_bank_account', 'bank_accounts', ['user_id', 'account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_bank_account', 'bank_accounts', type_='unique')
    op.drop_column('bank_accounts', 'account_number')
    # ### end Alembic commands ###
