"""update bank account uniqueness

Revision ID: 2fd5c4c62f03
Revises: 21843badd5fb
Create Date: 2026-08-12 14:30:09.985069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd5c4c62f03'
down_revision: Union[str, Sequence[str], None] = '21843badd5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_bank_account'), 'bank_accounts', type_='unique')
    op.create_unique_constraint('uq_user_bank_account_type', 'bank_accounts', ['user_id', 'bank_name', 'account_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_bank_account_type', 'bank_accounts', type_='unique')
    op.create_unique_constraint(op.f('uq_user_bank_account'), 'bank_accounts', ['user_id', 'account_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
