"""add income expense budget fields

Revision ID: 8423e918f76e
Revises: e8dc2c9173bc
Create Date: 2026-08-05 13:59:09.423621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8423e918f76e'
down_revision: Union[str, Sequence[str], None] = 'e8dc2c9173bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('notifications')
    op.drop_table('savings_goals')
    op.add_column('budgets', sa.Column('category', sa.String(), nullable=False))
    op.add_column('budgets', sa.Column('monthly_limit', sa.Float(), nullable=False))
    op.add_column('budgets', sa.Column('month_year', sa.String(), nullable=False))
    op.alter_column('budgets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('expenses', sa.Column('category', sa.String(), nullable=False))
    op.add_column('expenses', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('expenses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('date', sa.DateTime(), nullable=False))
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('incomes', sa.Column('source', sa.String(), nullable=False))
    op.add_column('incomes', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('incomes', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('incomes', sa.Column('date', sa.DateTime(), nullable=False))
    op.alter_column('incomes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_income_id'), table_name='incomes')
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.create_index(op.f('ix_income_id'), 'incomes', ['id'], unique=False)
    op.alter_column('incomes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('incomes', 'date')
    op.drop_column('incomes', 'notes')
    op.drop_column('incomes', 'amount')
    op.drop_column('incomes', 'source')
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('expenses', 'date')
    op.drop_column('expenses', 'description')
    op.drop_column('expenses', 'amount')
    op.drop_column('expenses', 'category')
    op.alter_column('budgets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('budgets', 'month_year')
    op.drop_column('budgets', 'monthly_limit')
    op.drop_column('budgets', 'category')
    op.create_table('savings_goals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('current_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.CheckConstraint('current_amount >= 0::numeric', name=op.f('savings_goals_current_amount_check')),
    sa.CheckConstraint('target_amount >= 0::numeric', name=op.f('savings_goals_target_amount_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('savings_goals_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'unread'::character varying"), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['unread'::character varying, 'read'::character varying]::text[])", name=op.f('notifications_status_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('generated_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_report_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    # ### end Alembic commands ###
