"""add bank account to incomes

Revision ID: d17081e323a3
Revises: 1d1529358e1e
Create Date: 2026-08-08 17:24:00.124425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17081e323a3'
down_revision: Union[str, Sequence[str], None] = '1d1529358e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incomes', 'bank_accounts', ['bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_column('incomes', 'bank_account_id')
    # ### end Alembic commands ###
